# Generated by Django 5.1.4 on 2025-06-17 18:29

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtchat", "0002_alter_chatgroup_group_name_messagereadstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagereadstatus",
            name="read_at",
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
    ]
